nomaya_social:
    buttons:
        facebook:
            url:            https://www.facebook.com/esprit.tn
            locale:         "fr_FR"
            send:           true
            width:          300
            showFaces:      true
            layout:         "button_count"
        twitter:
            url:            null
            locale:         "fr"
            message:        "Je veux partager ça avec vous"
            text:           "Tweet"
            via:            "L'Equipe cartedevisitevirtuelle.fr"
            tag:            "ttot"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:            
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    links: 
        facebook:           "http://www.facebook.com/"
        googleplus:         "https://plus.google.com/"
    theme:                  'default' # optional
