<?php

namespace Application\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarteFidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteFidRepository extends EntityRepository
{
 

    public function modify($id,$points)
    {
   $query=$this->getEntityManager()->createQuery("Update ProduitBundle:CarteFid c SET c.nbPoint=:points where c.id=:id ");
      $query->setParameter('id',$id);
        $query->setParameter('points',$points);
         $query->execute();
    }
    public function supp($id)
    {
 $query=$this->getEntityManager()->createQuery("Delete from ProduitBundle:CarteFid c where c.id=:id ");
        $query->setParameter('id',$id);
         $query->execute();

    }
}

